name: Generate Pacman Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pacman:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Publish pacman to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: pacman-output   
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
